import "server-only";

/**
 * Which AI provider is actually serving requests, decided once at module load
 * from server-only configuration.
 *
 * There are exactly three states and the product behaves correctly in all of
 * them. "deterministic" is not a degraded mode that shows an error; it is a
 * fully working product that composes its language from the same evidence a
 * model would have been given. The UI discloses which one produced any given
 * output rather than letting a reader assume.
 */
export type ProviderMode = "anthropic" | "deterministic" | "disabled";

export interface AIConfig {
  mode: ProviderMode;
  model: string | null;
  /** Human-readable reason for the current mode, safe to show in the product. */
  reason: string;
}

const DEFAULT_MODEL = "claude-sonnet-5";

export function getAIConfig(): AIConfig {
  // AI_DISABLED is an explicit off switch that outranks a present key, so an
  // operator can stop all model traffic without rotating credentials.
  if (process.env.AI_DISABLED === "true") {
    return {
      mode: "disabled",
      model: null,
      reason: "AI features are switched off for this environment.",
    };
  }

  const key = process.env.ANTHROPIC_API_KEY;
  if (key && key.trim().length > 0) {
    return {
      mode: "anthropic",
      model: process.env.ANTHROPIC_MODEL?.trim() || DEFAULT_MODEL,
      reason: "Narrative is generated by a model and reviewed by a person before it is used.",
    };
  }

  return {
    mode: "deterministic",
    model: null,
    reason:
      "No model provider is configured, so narrative is composed by deterministic rules from the same evidence. Nothing here is generated or estimated.",
  };
}

/** True when a live model could be called. Never leaks the key itself. */
export function isModelAvailable(): boolean {
  return getAIConfig().mode === "anthropic";
}
